openapi: 3.0.1
info:
  title: IT Wallet API - Employee Badge Authentic Source
  version: 0.2.0
  description: |
    # IT Wallet Authentic Source e-Service exposed via PDND.
    API for providing the data necessary to generate a Digital Employee Badge.
    The service allows for the retrieval of claims related to corporate and professional identity 
    in compliance with Schema.org standards (Organization/Person).
  termsOfService: "https://www.provider.example.it/terms/"
  contact:
    name: Digital Badge Technical Support
    url: "https://www.provider.example.it/support"
    email: helpdesk@provider.example.it
  x-api-id: ASITW-BGE-01
  x-summary: Universal Employee Badge Authentic Source.

servers:
  - url: https://api.provider.example.it/v0.2.0
    description: Production Server

tags:
  - name: status
    description: Endpoint for monitoring the health of the service.
  - name: credential
    description: Endpoint for the release of badge claims.

security:
  - BearerAuth: []

paths:
  /status:
    get:
      tags: [status]
      summary: Check status API
      description: Verifies the operational status of the Authentic Source.
      operationId: healthCheck
      responses:
        "200":
          description: Service active
          headers:
            Cache-Control: { $ref: "#/components/headers/CacheControlHeader" }
            X-RateLimit-Limit: { $ref: "#/components/headers/RateLimitLimitHeader" }
            X-RateLimit-Remaining: { $ref: "#/components/headers/RateLimitRemainingHeader" }
            X-RateLimit-Reset: { $ref: "#/components/headers/RateLimitResetHeader" }
          content:
            application/problem+json:
              schema: { $ref: "#/components/schemas/ProblemDetails" }
        "429":
          description: Too Many Requests
          headers:
            Retry-After: { $ref: "#/components/headers/RetryAfterHeader" }
          content:
            application/problem+json:
              schema: { $ref: "#/components/schemas/ProblemDetails" }
        "503":
          description: Service Unavailable
          headers:
            Retry-After: { $ref: "#/components/headers/RetryAfterHeader" }
          content:
            application/problem+json:
              schema: { $ref: "#/components/schemas/ProblemDetails" }

  /attribute-claims/employee-badge:
    post:
      tags: [credential]
      summary: Get Employee Badge Attribute Claims
      description: |
        Retrieves the attribute claims (Organization and PII) needed to generate the employee badge. 
        Requires message integrity through the INTEGRITY_REST_02 pattern.
      operationId: employeeBadgeClaims
      parameters:
        - $ref: "#/components/parameters/Agid-JWT-Signature"
        - $ref: "#/components/parameters/Digest"
        - $ref: "#/components/parameters/Agid-JWT-TrackingEvidence"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/CredentialClaimsRequest"
      responses:
        "200":
          description: OK - Claims successfully generated
          headers:
            Agid-JWT-Signature: 
              description: >-
                JWT containing the signature of the message headers whose integrity needs to be guaranteed, to comply with the INTEGRITY_REST_02 security pattern (see <a target="blank" href="https://italia.github.io/eid-wallet-it-docs/versione-corrente/en/e-service-pdnd.html">e-Service PDND</a>). <a target="blank" href="https://jwt.io/#debugger-io?token=ew0KICAiYWxnIjogIkVTMjU2IiwNCiAgImtpZCI6ICJhMWY1YzhkMi00YjM3LTRlOTEtYjBkMi03OWUzZjBjNGE4ZWYiLA0KICAidHlwIjogIkpXVCINCn0.ew0KICAiaXNzIjogIjEyMzRhYmNkLWVmNTYtZ2g3OC1pOWowLWtsbW5vcHFyc3R3eCIsDQogICJzdWIiOiAiMTIzNGFiY2QtZWY1Ni1naDc4LWk5ajAta2xtbm9wcXJzdHd4IiwNCiAgImF1ZCI6ICJodHRwczovL2ZydWl0b3JlLmV4YW1wbGUvZW50ZS1leGFtcGxlL3YxIiwNCiAgImlhdCI6IDE3MzMzOTc4NDAsDQogICJuYmYiOiAxNzMzNDAxNjI4LA0KICAiZXhwIjogMTczMzQwMTQ0MCwNCiAgImp0aSI6ICI4ZTEyZjRiNy05YzNhLTRmODMtOWI4ZC01MWEyYzdmNmU5ZDQiLA0KICAic2lnbmVkX2hlYWRlcnMiOiBbDQogICAgew0KICAgICAgImRpZ2VzdCI6ICJTSEEtMjU2PTc5YTIwYTc0NDMzNjQyMDMwMTgzMDYwMGFkOWJkY2E5OTM1OTNmODc2MjA5YTAwNGI1OTliNTgzMDk1YjBhNjEiDQogICAgfSwNCiAgICB7DQogICAgICAiY29udGVudC10eXBlIjogImFwcGxpY2F0aW9uL2pzb24iDQogICAgfQ0KICBdDQp9.DpuBNo2UgQhL7WLin4mpdZrbIpQq3tPvCX6HfktkxG7L5mk6a8OK1Hg0mQcZfFi3gelS-aL9kFS-6MoSy4csBg">EXAMPLE
              required: true
              schema:
                type: string
            Digest: 
              description: Digest of the message payload, to comply with the INTEGRITY_REST_02 security pattern. According to RFC 3230 Section 4.2 <a target="blank" href="https://www.rfc-editor.org/rfc/rfc3230.html#section-4.2">RFC 3230 §4.2</a>, the format MUST be the following digest-algorithm=encoded digest output.
              required: true
              schema:
                type: string
                example: SHA-256=79a20a744336420301830600ad9bdca993593f876209a004b599b583095b0a61
            Cache-Control: { $ref: "#/components/headers/CacheControlHeader" }
            X-RateLimit-Limit: { $ref: "#/components/headers/RateLimitLimitHeader" }
            X-RateLimit-Remaining: { $ref: "#/components/headers/RateLimitRemainingHeader" }
            X-RateLimit-Reset: { $ref: "#/components/headers/RateLimitResetHeader" }
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/BadgeResponse"
        "400":
          description: Bad Request
          headers:
            X-RateLimit-Limit: { $ref: "#/components/headers/RateLimitLimitHeader" }
            X-RateLimit-Remaining: { $ref: "#/components/headers/RateLimitRemainingHeader" }
            X-RateLimit-Reset: { $ref: "#/components/headers/RateLimitResetHeader" }
          content:
            application/problem+json:
              schema: { $ref: "#/components/schemas/ProblemDetails" }
        "401":
          description: Unauthorized
          headers:
            X-RateLimit-Limit: { $ref: "#/components/headers/RateLimitLimitHeader" }
            X-RateLimit-Remaining: { $ref: "#/components/headers/RateLimitRemainingHeader" }
            X-RateLimit-Reset: { $ref: "#/components/headers/RateLimitResetHeader" }
            WWW-Authenticate: { $ref: "#/components/headers/WWWAuthenticateHeader" }
          content:
            application/problem+json:
              schema: { $ref: "#/components/schemas/ProblemDetails" }
        "404":
          description: Claims not found
          headers:
            X-RateLimit-Limit: { $ref: "#/components/headers/RateLimitLimitHeader" }
            X-RateLimit-Remaining: { $ref: "#/components/headers/RateLimitRemainingHeader" }
            X-RateLimit-Reset: { $ref: "#/components/headers/RateLimitResetHeader" }
          content:
            application/problem+json:
              schema: { $ref: "#/components/schemas/ProblemDetails" }
        "429":
          description: Too Many Requests
          headers:
            Retry-After: { $ref: "#/components/headers/RetryAfterHeader" }
          content:
            application/problem+json:
              schema: { $ref: "#/components/schemas/ProblemDetails" }
        "500":
          description: Internal Server Error
          headers:
            Retry-After: { $ref: "#/components/headers/RetryAfterHeader" }
          content:
            application/problem+json:
              schema: { $ref: "#/components/schemas/ProblemDetails" }
        "503":
          description: Service Unavailable
          headers:
            Retry-After: { $ref: "#/components/headers/RetryAfterHeader" }
          content:
            application/problem+json:
              schema: { $ref: "#/components/schemas/ProblemDetails" }

components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
      description: PDND Bearer Token

  parameters:
    Agid-JWT-Signature:
      name: Agid-JWT-Signature
      in: header
      description: >-
        JWT containing the signature of the message headers whose integrity
        needs to be guaranteed, to comply with the INTEGRITY_REST_02
        security pattern (see <a target="blank"
        href="https://italia.github.io/eid-wallet-it-docs/versione-corrente/en/e-service-pdnd.html">e-Service PDND</a>). <br/><br/>

        <a target="blank" href="https://jwt.io/#debugger-io?token=eyJhbGciOiJFUzI1NiIsImtpZCI6ImQ0YzNiMmExLTk4NzYtNTQzMi0xMGZlLWRjYmE5ODc2NTQzMiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiI4MjkxNGIzZi02MGIyLTQ1MjktYjRkNi0zZDRlNjdmMGE5MzMiLCJzdWIiOiI4MjkxNGIzZi02MGIyLTQ1MjktYjRkNi0zZDRlNjdmMGE5MzMiLCJhdWQiOiJodHRwczovL2F1dGhlbnRpYy1zb3VyY2UuZXhhbXBsZS5pdCIsImlhdCI6MTczMzM5Nzg0MCwibmJmIjoxNzMzNDAxNjI4LCJleHAiOjE3MzM0MDE0NDAsImp0aSI6ImQzZjdiMmM5LTI3NGEtNDJiNy04ZjhkLTJlOWQ4YjE3MzRiMCIsInNpZ25lZF9oZWFkZXJzIjpbeyJkaWdlc3QiOiJTSEEtMjU2PTcyZTE4YmRkZGYxM2M5MTFiNGRkNTYyZWUyMTk3OWE1YzlmMjM1YzNhMDFiZDE0MjZlODU3ZDhjMWEyODJmNDEifSx7ImNvbnRlbnQtdHlwZSI6ImFwcGxpY2F0aW9uL2pzb24ifV19.tG5-P96CCA6N1IYC-xk4GumoVkA3NFolpbBn2vQ2e9vpWQ8f5Sm2l4-1VrXfKTx-CUVz_puiwqkBhulrNKj2fA">EXAMPLE
        ON JWT.IO</a>
      required: true
      schema:
        type: string
        format: JWT
        example: eyJhbGciOiJFUzI1NiIsImtpZCI6ImQ0YzNiMmExLTk4NzYtNTQzMi0xMGZlLWRjYmE5ODc2NTQzMiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiI4MjkxNGIzZi02MGIyLTQ1MjktYjRkNi0zZDRlNjdmMGE5MzMiLCJzdWIiOiI4MjkxNGIzZi02MGIyLTQ1MjktYjRkNi0zZDRlNjdmMGE5MzMiLCJhdWQiOiJodHRwczovL2F1dGhlbnRpYy1zb3VyY2UuZXhhbXBsZS5pdCIsImlhdCI6MTczMzM5Nzg0MCwibmJmIjoxNzMzNDAxNjI4LCJleHAiOjE3MzM0MDE0NDAsImp0aSI6ImQzZjdiMmM5LTI3NGEtNDJiNy04ZjhkLTJlOWQ4YjE3MzRiMCIsInNpZ25lZF9oZWFkZXJzIjpbeyJkaWdlc3QiOiJTSEEtMjU2PTcyZTE4YmRkZGYxM2M5MTFiNGRkNTYyZWUyMTk3OWE1YzlmMjM1YzNhMDFiZDE0MjZlODU3ZDhjMWEyODJmNDEifSx7ImNvbnRlbnQtdHlwZSI6ImFwcGxpY2F0aW9uL2pzb24ifV19.tG5-P96CCA6N1IYC-xk4GumoVkA3NFolpbBn2vQ2e9vpWQ8f5Sm2l4-1VrXfKTx-CUVz_puiwqkBhulrNKj2fA
    Digest:
      name: Digest
      in: header
      description: >-
        Digest of the message payload, to comply with the INTEGRITY_REST_02
        security pattern. According to <a target="blank" href="https://www.rfc-editor.org/rfc/rfc3230.html#section-4.2">RFC
        3230 §4.2</a>, the format MUST be the following: digest-algorithm=encoded
        digest output.
      required: true
      schema:
        type: string
        example: SHA-256=72e18bdddf13c911b4dd562ee21979a5c9f235c3a01bd1426e857d8c1a282f41
    Agid-JWT-TrackingEvidence:
      name: Agid-JWT-TrackingEvidence
      in: header
      description: >-
        If the Voucher type is Bearer, this header represents a JWT acting as a proof of possession, to comply with the REST_JWS_2021_POP security
        pattern using the POP_TPoP implementation. Otherwise, it is a JWT containing the data tracked in the Consumer's domain, to comply with AUDIT_REST_02 (see <a target="blank"
        href="https://italia.github.io/eid-wallet-it-docs/versione-corrente/en/e-service-pdnd.html">e-Service PDND</a>). <br/><br/>
        <a target="blank" href="https://jwt.io/#debugger-io?token=eyJhbGciOiJFUzI1NiIsImtpZCI6ImQ0YzNiMmExLTk4NzYtNTQzMi0xMGZlLWRjYmE5ODc2NTQzMiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiI4MjkxNGIzZi02MGIyLTQ1MjktYjRkNi0zZDRlNjdmMGE5MzMiLCJzdWIiOiI4MjkxNGIzZi02MGIyLTQ1MjktYjRkNi0zZDRlNjdmMGE5MzMiLCJhdWQiOiJodHRwczovL2F1dGhlbnRpYy1zb3VyY2UuZXhhbXBsZS5pdCIsImV4cCI6MTczMzA1MjYwMCwibmJmIjoxNzMzMDM2NDUwLCJpYXQiOjE3MzMwMzY0MDAsImp0aSI6ImE0YjVjNmQ3LWU4ZjktYWJjZC1lZjEyLTM0NTY3ODkwMTIzNCIsImRub25jZSI6NjUyODQyNDIxMzY4NSwicHVycG9zZUlkIjoiYjJjM2Q0ZTUtZjZnNy1oOGk5LWowazEtbG1ubzEyMzQ1Njc4IiwidXNlcklEIjoiYThiN2M2ZDUtZTRmMy1nMmgxLWk5ajAta2xtbm9wcXJzdHV2IiwibG9hIjoic3Vic3RhbnRpYWwifQ.y42yfMeW2H9h0b0j0BODUml8yF20stY9q3BwoVU5BB90afBj852Q0QlInncdhjXhUjLS1V76cGBxkutDNvxRNA">EXAMPLE
        ON JWT.IO</a>
      required: false
      schema:
        type: string
        format: JWT
        example: eyJhbGciOiJFUzI1NiIsImtpZCI6ImQ0YzNiMmExLTk4NzYtNTQzMi0xMGZlLWRjYmE5ODc2NTQzMiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiI4MjkxNGIzZi02MGIyLTQ1MjktYjRkNi0zZDRlNjdmMGE5MzMiLCJhdWQiOiJodHRwczovL2F1dGhlbnRpYy1zb3VyY2UuZXhhbXBsZS5pdCIsImlhdCI6MTczMzM5Nzg0MCwibmJmIjoxNzMzNDAxNjI4LCJleHAiOjE3MzM0MDE0NDAsImp0aSI6ImQzZjdiMmM5LTI3NGEtNDJiNy04ZjhkLTJlOWQ4YjE3MzRiMCIsInNpZ25lZF9oZWFkZXJzIjpbeyJkaWdlc3QiOiJTSEEtMjU2PTcyZTE4YmRkZGYxM2M5MTFiNGRkNTYyZWUyMTk3OWE1YzlmMjM1YzNhMDFiZDE0MjZlODU3ZDhjMWEyODJmNDEifSx7ImNvbnRlbnQtdHlwZSI6ImFwcGxpY2F0aW9uL2pzb24ifV19.tG5-P96CCA6N1IYC-xk4GumoVkA3NFolpbBn2vQ2e9vpWQ8f5Sm2l4-1VrXfKTx-CUVz_puiwqkBhulrNKj2fA

  headers:
    CacheControlHeader:
      description: RFC 7234 directive (no-store for sensitive data).
      schema: { type: string, enum: [no-store] }
    RateLimitLimitHeader:
      description: Maximum number of requests allowed in the time window.
      schema: { type: integer, format: int32, minimum: 0 }
    RateLimitRemainingHeader:
      description: Number of requests remaining in the time window.
      schema: { type: integer, format: int32, minimum: 0 }
    RateLimitResetHeader:
      description: UTC Epoch in seconds, corresponding to the time when the limit will be reset.
      schema: { type: integer, format: int32, minimum: 0 }
    RetryAfterHeader:
      description: Seconds to wait before making a new request (RFC 6585).
      schema: { type: integer, format: int32, minimum: 0 }
    WWWAuthenticateHeader:
      description: Indicates that the request cannot be satisfied because the Voucher is expired or invalid.
      schema: { type: string, example: 'Bearer error="invalid_token", error_description="The access token expired"' }

  schemas:
    CredentialClaimsRequest:
      type: object
      required: [unique_id]
      properties:
        unique_id:
          type: string
          description: Unique identifier of the employee (e.g., Tax ID).

    BadgeResponse:
      type: object
      required: [userClaims, attributeClaims, metadataClaims]
      properties:
        userClaims:
          type: object
          properties:
            given_name: { type: string, example: "Mario" }
            family_name: { type: string, example: "Rossi" }
            birth_date: { type: string, format: date }
            birth_place: { type: string, example: "Rome" }
            tax_id_code: { type: string, example: "TINIT-RSSMRO75E05H501Z" }
        attributeClaims:
          type: array
          items:
            $ref: "#/components/schemas/EmployeeAttributeClaims"
        metadataClaims:
          type: array
          items:
            $ref: "#/components/schemas/MetadataClaims"
        interval:
          type: integer
          format: int64
          example: 864000

    EmployeeAttributeClaims:
      type: object
      required: [object_id, status, last_updated, legalName, identifier, logo, image]
      properties:
        object_id: { type: string, description: "Unique identifier of the Dataset." }
        status: 
          type: string
          enum: [VALID, INVALID, SUSPENDED]
          description: Status of the Dataset.
        last_updated: { type: string, format: date-time, description: "Last update of the Dataset." }
        # Organization Claims
        legalName: { type: string, description: "Organization Name" }
        legalAddress: { type: string, description: "Organization postal address" }
        location: { type: string, description: "Location or geographic area" }
        logo: { type: string, format: byte, description: "Corporate logo (Base64)" }
        vatID: { type: string, description: "Organization VAT ID" }
        # Employee/PII Claims
        identifier: { type: string, description: "Unique employee identifier" }
        jobTitle: { type: string, description: "Professional job title" }
        honorificPrefix: { type: string, description: "Ex: Dr./Mr./Ms." }
        email: { type: string, format: email, description: "Professional email address" }
        telephone: { type: string, description: "Professional telephone number" }
        image: { type: string, format: byte, description: "Professional's photo (Base64)" }
        address: { type: string, description: "Individual postal address" }

    MetadataClaims:
      type: object
      required: [object_id, issuance_date, expiry_date]
      properties:
        object_id: { type: string, description: "Unique identifier of the Dataset." }
        issuance_date: { type: string, format: date, description: "Administrative validity start date of the Dataset." }
        expiry_date: { type: string, format: date, description: "Administrative expiry date of the Dataset." }

    ProblemDetails:
      type: object
      description: Object conforming to RFC7807 for error reporting.
      properties:
        type:
          type: string
          format: uri
          description: Absolute URI identifying the problem type.
        title:
          type: string
          description: Short human-readable summary of the problem type.
        status:
          type: integer
          format: int32
          description: HTTP status code generated for this occurrence of the problem.
        detail:
          type: string
          description: Detailed human-readable explanation specific to this occurrence of the problem.
        instance:
          type: string
          format: uri
          description: Absolute URI identifying the specific occurrence of the problem.
      required: [title, status, detail]
